<ul class="localnavi">
<li><a href="/">/</a></li>
<li><a href="/cat01/">cat01/</a><ul>
		<li><a href="/cat01/page01.html">page01.html</a></li>
		<li><a href="/cat01/page02.html">page02.html</a><ul>
				<li><a href="/cat01/childpage01.html">childpage01.html</a></li>
				<li><a href="/cat01/childpage02.html">childpage02.html</a></li>
			</ul></li>
		<li><a href="/cat01/page03.html">page03.html</a></li>
	</ul></li>
<li><a href="/cat02/index.html">cat02/index.html</a><ul>
		<li><a href="/cat02/page01.html">page01.html</a></li>
		<li><a href="/cat02/child01/">child01/</a><ul>
				<li><a href="/cat02/child01/childpage01.html">childpage01.html</a></li>
				<li><a href="/cat02/child01/childpage02.html">childpage02.html</a></li>
			</ul></li>
		<li>child02/<ul>
				<li><a href="/cat02/child02/">index.html</a></li>
				<li><a href="/cat02/child02/childpage01.html">childpage01.html</a></li>
			</ul></li>
		<li><a href="/cat02/page02.html">page02.html</a></li>
	</ul></li>
<li><a href="/cat03/">cat03/index.html</a></li>
<li><a href="/cat05/">cat04/</a><ul>
		<li><a href="/cat04/page01.php">page01.php</a></li>
		<li><a href="/cat04/page02.htm">page02.htm</a></li>
		<li><a href="/cat04/page03.shtml">page03.shtml</a></li>
		<li><a href="/cat04/page04.shtm">page04.shtm</a></li>
		<li><a href="/cat04/page05.php?id=hoge">page05.php?id=hoge</a></li>
		<li><a href="/cat04/page05.php?id=hoge&amp;fuga=fuga">page05.php?id=hoge&amp;fuga=fuga</a></li>
		<li><a href="/cat04/page06.html?id=hoge&amp;fuga=fuga">page06.html?id=hoge&amp;fuga=fuga</a></li>
	</ul></li>
<li><a href="/cat05/">cat05/</a><ul>
		<li><a href="/cat05/index.html?cat=01">index.html?cat=01</a></li>
		<li><a href="/cat05/index.html?cat=02">index.html?cat=02</a></li>
		<li><a href="/cat05/index.html?cat=03">index.html?cat=03</a></li>
	</ul></li>
</ul>